language: python
sudo: true
python:
#  - "2.6"
  - "2.7"

services:
  - mongodb


# command to install dependencies
# some are only used for travis/coveralls so we are installing them here only
install:
  - ./test/setup_test.sh
# command to run tests
# notice: the nose-cov is used because it is compatible with --processes, but produce a .coverage by process
# so we must combine them in the end
script:
  - pip freeze  # so to help eventual debug: know what exact versions are in use can be rather useful.
  # Code static analysis
  - pycodestyle --max-line-length=100 --exclude='*.pyc, *.cfg, *.log' --ignore='E402' --ignore='W504' alignak_module_backend/*
  - pylint --rcfile=.pylintrc alignak_module_backend/*
  # Code dynamic analysis
  - cd test
  # Delete previously existing coverage results
  - coverage erase
  # Run test suite with py.test running its coverage plugin
  # Report about coverage
  - pytest --cov=alignak_module_backend --cov-report term-missing --cov-config .coveragerc test_*.py
  - coverage report -m
  - cd ..
after_success:
  # to get coverage data with relative paths and not absolute we have to
  # execute coveralls from the base directory of the project,
  # so we need to move the .coverage file here :
  - mv test/.coverage . && coveralls --rcfile=test/.coveragerc -v
  - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION

deploy:
  - provider: bintray
    skip_cleanup: true
    file: .bintray.json
    user: ddurieux
    key:
      secure: "AMABxlOeqkSszJt2kp0ZbwuCbBnTgPlLN27/Exi/Bxab3gbjQN2zR0X/D3ReeoPREjgFGqVrgPSYK54aj6HHDxNI+WH8yI0dIXFgCso5QXsLbwLm+OSyfYxz0Mef8CzQq3CbVcGQ1beoVw75pKWsT36tu2Wi+yD5OPg48szGkuj4BQ35GpEldS1EEj6iVF0e6yafY0SOzRMrYYC9k+ik3Rnz39RkDsA1T07OVQMFvlL2IP3dl2qKO+OrXDJP6z9KI1zdRhNjqMhglB8rkOue8FxF+x+Gol9C2kJAtRKGq8EZltyG4AEbHr6LIiIMU0lE9XZX/RykiQN0bG/J+CM6lrgfU6yce6UEYeSDxPyCaRZiKaWWSOYVtpB73wwJ5mGwE8SM1mXve2p+Ap7d8TlTFzCK/AlS38GIg9LgwRnhqFdvrL5nLRayCSHo4IcxroIxlldzBUaV2APpjeIb5WH5MI/QHQViKwqoMl2RJJRF1e+k4fkS6FBaiDKtT3ALizrnX2elKZOpcfFb+fr9ydcTHaznk6wGnPZcMON9npyl6QOh/OKbzbdbfqGLW5aTnGRu4MBLmR+N2aTl83p6nQmw5jpy0TuF1BHthC7GkiS49sXVLzyhVhbbGstHX1Oa72JnBbu5xk46nDqJCXPY8c7RNkRGbO9LiJnWzogM6exb8T4="
    on:
      branch: develop
  - provider: bintray
    skip_cleanup: true
    file: .bintray.json
    user: ddurieux
    key:
      secure: "AMABxlOeqkSszJt2kp0ZbwuCbBnTgPlLN27/Exi/Bxab3gbjQN2zR0X/D3ReeoPREjgFGqVrgPSYK54aj6HHDxNI+WH8yI0dIXFgCso5QXsLbwLm+OSyfYxz0Mef8CzQq3CbVcGQ1beoVw75pKWsT36tu2Wi+yD5OPg48szGkuj4BQ35GpEldS1EEj6iVF0e6yafY0SOzRMrYYC9k+ik3Rnz39RkDsA1T07OVQMFvlL2IP3dl2qKO+OrXDJP6z9KI1zdRhNjqMhglB8rkOue8FxF+x+Gol9C2kJAtRKGq8EZltyG4AEbHr6LIiIMU0lE9XZX/RykiQN0bG/J+CM6lrgfU6yce6UEYeSDxPyCaRZiKaWWSOYVtpB73wwJ5mGwE8SM1mXve2p+Ap7d8TlTFzCK/AlS38GIg9LgwRnhqFdvrL5nLRayCSHo4IcxroIxlldzBUaV2APpjeIb5WH5MI/QHQViKwqoMl2RJJRF1e+k4fkS6FBaiDKtT3ALizrnX2elKZOpcfFb+fr9ydcTHaznk6wGnPZcMON9npyl6QOh/OKbzbdbfqGLW5aTnGRu4MBLmR+N2aTl83p6nQmw5jpy0TuF1BHthC7GkiS49sXVLzyhVhbbGstHX1Oa72JnBbu5xk46nDqJCXPY8c7RNkRGbO9LiJnWzogM6exb8T4="
    on:
      tags: true
